<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\Admin;
use App\Models\HasilKuesioner;
use App\Models\DataDiris;
use App\Models\MentalHealthJawabanDetail;
use Illuminate\Foundation\Testing\RefreshDatabase;

/**
 * Test untuk fitur Cetak PDF Detail Jawaban
 * Coverage: Pf-73 s/d Pf-76
 *
 * Note: Karena PDF generation menggunakan jsPDF (client-side JavaScript),
 * test ini memverifikasi bahwa:
 * 1. Halaman detail dapat diakses dengan benar
 * 2. Data yang diperlukan untuk PDF tersedia di view
 * 3. Script jsPDF dan autotable dimuat
 * 4. Elemen-elemen untuk generate PDF ada di halaman
 */
class AdminCetakPdfTest extends TestCase
{
    use RefreshDatabase;

    protected Admin $admin;
    protected HasilKuesioner $hasilKuesioner;
    protected DataDiris $dataDiri;

    protected function setUp(): void
    {
        parent::setUp();

        // Buat admin
        $this->admin = Admin::factory()->create();

        // Buat data mahasiswa lengkap
        $this->dataDiri = DataDiris::factory()->create([
            'nim' => '123456789',
            'nama' => 'John Doe',
            'jenis_kelamin' => 'L',
            'provinsi' => 'Lampung',
            'alamat' => 'Jl. Test No. 123',
            'usia' => 20,
            'fakultas' => 'FTIK',
            'program_studi' => 'Teknik Informatika',
            'asal_sekolah' => 'SMA',
            'status_tinggal' => 'Kost',
            'email' => 'john@example.com'
        ]);

        // Buat hasil kuesioner
        $this->hasilKuesioner = HasilKuesioner::factory()->create([
            'nim' => '123456789',
            'total_skor' => 180,
            'kategori' => 'Sehat'
        ]);

        // Buat 38 detail jawaban
        for ($i = 1; $i <= 38; $i++) {
            MentalHealthJawabanDetail::create([
                'hasil_kuesioner_id' => $this->hasilKuesioner->id,
                'nomor_soal' => $i,
                'skor' => ($i % 6) + 1
            ]);
        }
    }

    /**
     * Pf-73: Menguji generate PDF detail jawaban dengan data valid
     */
    public function test_generate_pdf_detail_jawaban_dengan_data_valid()
    {
        $response = $this->actingAs($this->admin, 'admin')
            ->get(route('admin.mental-health.detail', $this->hasilKuesioner->id));

        $response->assertStatus(200);

        // Pastikan view dimuat dengan benar
        $response->assertViewIs('admin-mental-health-detail');

        // Pastikan data yang diperlukan untuk PDF ada di view
        $response->assertViewHas('hasil');
        $response->assertViewHas('jawabanDetails');

        // Pastikan script jsPDF dimuat
        $response->assertSee('jspdf.umd.min.js', false);
        $response->assertSee('jspdf.plugin.autotable.min.js', false);

        // Pastikan tombol cetak PDF ada
        $response->assertSee('Cetak PDF');
        $response->assertSee('printDetail()');
    }

    /**
     * Pf-74: Menguji konten PDF berisi header, info mahasiswa, dan tabel jawaban
     */
    public function test_konten_pdf_berisi_header_info_mahasiswa_dan_tabel_jawaban()
    {
        $response = $this->actingAs($this->admin, 'admin')
            ->get(route('admin.mental-health.detail', $this->hasilKuesioner->id));

        $response->assertStatus(200);

        // Verifikasi data mahasiswa tersedia untuk PDF
        $response->assertSee('John Doe');
        $response->assertSee('123456789');
        $response->assertSee('Teknik Informatika');

        // Verifikasi data hasil kuesioner tersedia
        $response->assertSee('180');
        $response->assertSee('Sehat');

        // Verifikasi tabel jawaban tersedia (38 pertanyaan)
        $response->assertViewHas('jawabanDetails', function ($details) {
            return $details->count() === 38;
        });

        // Verifikasi struktur data untuk tabel tersedia
        $response->assertViewHas('jawabanDetails');
        $response->assertViewHas('questions');
    }

    /**
     * Pf-75: Menguji watermark "Generated by ANALOGY - ITERA" pada PDF
     */
    public function test_watermark_generated_by_analogy_itera_pada_pdf()
    {
        $response = $this->actingAs($this->admin, 'admin')
            ->get(route('admin.mental-health.detail', $this->hasilKuesioner->id));

        $response->assertStatus(200);

        // Verifikasi watermark text ada di JavaScript function
        $response->assertSee('Generated by ANALOGY - ITERA', false);
    }

    /**
     * Pf-76: Menguji format tabel PDF dengan 38 pertanyaan lengkap
     */
    public function test_format_tabel_pdf_dengan_38_pertanyaan_lengkap()
    {
        $response = $this->actingAs($this->admin, 'admin')
            ->get(route('admin.mental-health.detail', $this->hasilKuesioner->id));

        $response->assertStatus(200);

        // Verifikasi semua 38 jawaban ada
        $response->assertViewHas('jawabanDetails', function ($details) {
            if ($details->count() !== 38) {
                return false;
            }

            // Verifikasi nomor soal 1-38 semua ada
            $nomorSoal = $details->pluck('nomor_soal')->toArray();
            for ($i = 1; $i <= 38; $i++) {
                if (!in_array($i, $nomorSoal)) {
                    return false;
                }
            }

            return true;
        });

        // Verifikasi data terstruktur untuk tabel
        $response->assertViewHas('jawabanDetails', function ($details) {
            foreach ($details as $detail) {
                // Setiap detail harus punya nomor_soal dan skor
                if (!isset($detail->nomor_soal) || !isset($detail->skor)) {
                    return false;
                }
            }
            return true;
        });
    }

    /**
     * Test: PDF hanya bisa digenerate oleh admin yang terautentikasi
     */
    public function test_pdf_hanya_bisa_diakses_oleh_admin_terautentikasi()
    {
        // Akses tanpa login
        $response = $this->get(route('admin.mental-health.detail', $this->hasilKuesioner->id));

        $response->assertRedirect(route('login'));
    }

    /**
     * Test: PDF tidak bisa digenerate untuk data yang tidak ada
     */
    public function test_pdf_tidak_bisa_digenerate_untuk_data_tidak_ada()
    {
        $response = $this->actingAs($this->admin, 'admin')
            ->get(route('admin.mental-health.detail', 99999));

        $response->assertStatus(404);
    }

    /**
     * Test: Data mahasiswa lengkap tersedia untuk header PDF
     */
    public function test_data_mahasiswa_lengkap_tersedia_untuk_header_pdf()
    {
        $response = $this->actingAs($this->admin, 'admin')
            ->get(route('admin.mental-health.detail', $this->hasilKuesioner->id));

        $response->assertStatus(200);

        // Verifikasi view memiliki variable hasil
        $response->assertViewHas('hasil');

        // Verifikasi data tampil di halaman
        $response->assertSee('John Doe');
        $response->assertSee('123456789');
        $response->assertSee('Teknik Informatika');
    }

    /**
     * Test: Klasifikasi item positif dan negatif tersedia untuk PDF
     */
    public function test_klasifikasi_item_positif_negatif_tersedia_untuk_pdf()
    {
        $response = $this->actingAs($this->admin, 'admin')
            ->get(route('admin.mental-health.detail', $this->hasilKuesioner->id));

        $response->assertStatus(200);

        // Item negatif dan positif harus terdefinisi di view
        $itemNegatif = [2, 3, 8, 9, 11, 13, 14, 15, 16, 18, 19, 20, 21, 24, 25, 27, 28, 29, 30, 32, 33, 35, 36, 38];
        $itemPositif = [1, 4, 5, 6, 7, 10, 12, 17, 22, 23, 26, 31, 34, 37];

        $response->assertViewHas('jawabanDetails', function ($details) use ($itemNegatif, $itemPositif) {
            foreach ($details as $detail) {
                $nomor = $detail->nomor_soal;

                // Setiap item harus masuk salah satu klasifikasi
                $isNegative = in_array($nomor, $itemNegatif);
                $isPositive = in_array($nomor, $itemPositif);

                if (!$isNegative && !$isPositive) {
                    return false;
                }
            }
            return true;
        });
    }

    /**
     * Test: Timestamp dan tanggal tersedia untuk footer PDF
     */
    public function test_timestamp_tanggal_tersedia_untuk_footer_pdf()
    {
        $response = $this->actingAs($this->admin, 'admin')
            ->get(route('admin.mental-health.detail', $this->hasilKuesioner->id));

        $response->assertStatus(200);

        // Verifikasi created_at tersedia
        $response->assertViewHas('hasil', function ($hasil) {
            return $hasil->created_at !== null;
        });

        // Verifikasi JavaScript untuk timestamp ada
        $response->assertSee('toLocaleDateString', false);
        $response->assertSee('Dicetak:', false);
    }
}
